-- 1. Таблица клиентов (множественное число customers)
CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Аналог AUTO_INCREMENT в Postgres
                           name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           created_at TIMESTAMP -- В Postgres тип называется TIMESTAMP, а не datetime
);

-- 2. Таблица заказов (множественное число orders)
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,          -- Ссылка на клиента
                        amount DECIMAL(19, 2) NOT NULL,       -- Для денег всегда указываем точность
                        order_status VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP,

    -- Создаем связь (Foreign Key): заказ не может существовать без клиента
                        CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);